--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Discriminator" text NOT NULL,
    "Description" text,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Surname" character varying(255) NOT NULL,
    "RoleName" text,
    "Status" integer NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- Name: CheckList; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CheckList" (
    "Id" integer NOT NULL,
    "ListName" text NOT NULL,
    "ListPostion" text NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "LastModficationDate" timestamp without time zone NOT NULL,
    "Status" integer NOT NULL,
    "UserId" text,
    "ShopPrice" real DEFAULT 0 NOT NULL
);


ALTER TABLE public."CheckList" OWNER TO postgres;

--
-- Name: CheckList_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CheckList" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CheckList_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserAuthorisation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserAuthorisation" (
    "Id" integer NOT NULL,
    "UserGuid" text,
    "Status" integer NOT NULL,
    "RegistryDate" timestamp without time zone NOT NULL,
    "ExpireDate" timestamp without time zone NOT NULL
);


ALTER TABLE public."UserAuthorisation" OWNER TO postgres;

--
-- Name: UserAuthorisation_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserAuthorisation" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserAuthorisation_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UsersLoginHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UsersLoginHistory" (
    "Id" integer NOT NULL,
    "UserId" text,
    "LoginDate" timestamp without time zone NOT NULL
);


ALTER TABLE public."UsersLoginHistory" OWNER TO postgres;

--
-- Name: UsersLoginHistory_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UsersLoginHistory" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UsersLoginHistory_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Discriminator", "Description", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
118984c9-9942-4be2-af78-a6a2215593aa	Role	Perform normal operations.	NormalUser	NORMALUSER	b2059222-0db6-42a5-9fb3-a7b56ea00d0a
0929c2c3-5a62-4b6d-af66-f71fc2e42ffe	Role	Perform all the operations.	Admin	ADMIN	9c511f77-dee5-47e6-ac11-327af9227eec
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
f1634e81-9816-426f-8f64-a1d34c3f3cb3	118984c9-9942-4be2-af78-a6a2215593aa
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "Name", "Surname", "RoleName", "Status", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
132401bf-afa5-48f0-81bc-3c7b0bf8e2b4	Tester	Tester	\N	0	Tester	TESTER	Tester@serwis.com	TESTER@SERWIS.COM	f	AQAAAAEAACcQAAAAEEdVujxkjuLNejhSxNpj0TUg0hZJ6RwPF8P/R+hIcmhG+CKTBZ++XHxAPqqGTU6SmQ==	FSSG42A5WGSLSSLBIS4KG5JO2ITULYU6	f4765e8b-7db7-4056-8ab5-2f2302399ea0	\N	f	f	\N	t	0
aa957e32-eac8-4c9f-8bf5-946d1b1701bc	Admin	Admin	0929c2c3-5a62-4b6d-af66-f71fc2e42ffe	0	Admin	ADMIN	admin@localhost	ADMIN@LOCALHOST	f	AQAAAAEAACcQAAAAEEvgbNjdkyyGjzjXL4nZZbscZONzEUz/ISc9YAWFAeLgOX26Enw6L2greQnE+CpRLg==	C5KGOOAD2WFGE2TZ56QDC4VRAUJ5GMLH	47e86438-917d-43e2-b505-5626526409b4	\N	f	f	\N	t	0
f1634e81-9816-426f-8f64-a1d34c3f3cb3	Tester1	Tester	118984c9-9942-4be2-af78-a6a2215593aa	0	Tester1	TESTER1	Tester1@serwis.com	TESTER1@SERWIS.COM	f	AQAAAAEAACcQAAAAEHZGwgDLGnolWVVLC7lXb/o9NBL5KVEUgxuAzrs8sjG6Fk9fwqYtkxo4nLGG8ZKUwQ==	EGBVYPESRAXZB4GL77D75FF3R5HN2BHY	2be0b883-f241-415e-8d82-a5fed62bba41	\N	f	f	\N	t	0
\.


--
-- Data for Name: CheckList; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CheckList" ("Id", "ListName", "ListPostion", "CreationDate", "LastModficationDate", "Status", "UserId", "ShopPrice") FROM stdin;
3	Test	Tester	2021-05-13 21:31:15.674467	2021-05-13 21:31:15.674467	2	aa957e32-eac8-4c9f-8bf5-946d1b1701bc	0
5	Test	Tester	2021-05-14 09:44:24.905098	2021-05-14 09:44:24.905098	0	f1634e81-9816-426f-8f64-a1d34c3f3cb3	0
6	Test	Tester	2021-05-14 09:44:24.905098	2021-05-14 09:44:24.905098	2	aa957e32-eac8-4c9f-8bf5-946d1b1701bc	0
7	Test	Tester	2021-05-14 11:19:08.503803	2021-05-14 11:19:08.503803	2	aa957e32-eac8-4c9f-8bf5-946d1b1701bc	0
8	Test	Tester	2021-05-14 11:20:03.376554	2021-05-14 11:20:03.376554	0	f1634e81-9816-426f-8f64-a1d34c3f3cb3	0
4	Test	Tester	2021-05-14 07:36:21.166814	2021-05-14 12:17:00.508343	1	f1634e81-9816-426f-8f64-a1d34c3f3cb3	10
\.


--
-- Data for Name: UserAuthorisation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserAuthorisation" ("Id", "UserGuid", "Status", "RegistryDate", "ExpireDate") FROM stdin;
\.


--
-- Data for Name: UsersLoginHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UsersLoginHistory" ("Id", "UserId", "LoginDate") FROM stdin;
1	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-12 21:16:05.46503
2	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-13 20:17:44.067913
3	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-13 20:55:36.442534
4	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-13 21:13:45.769427
5	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-13 21:31:00.61378
6	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-13 21:48:17.74267
7	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-13 22:02:16.128164
8	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 07:34:47.1654
9	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 07:55:39.781187
10	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 09:42:29.10467
11	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 10:03:04.270297
12	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 11:17:45.434392
13	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 11:38:11.646518
14	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 11:42:46.620911
15	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 12:12:22.211637
16	f1634e81-9816-426f-8f64-a1d34c3f3cb3	2021-05-14 12:37:18.979655
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20210512134340_Init-Database	5.0.6
20210513045541_CheckList-init	5.0.6
20210513130408_CheckList-Add-ShopPrice	5.0.6
20210513192947_CheckList-Add-UserId	5.0.6
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: CheckList_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CheckList_Id_seq"', 9, true);


--
-- Name: UserAuthorisation_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserAuthorisation_Id_seq"', 1, false);


--
-- Name: UsersLoginHistory_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UsersLoginHistory_Id_seq"', 16, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: CheckList PK_CheckList; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CheckList"
    ADD CONSTRAINT "PK_CheckList" PRIMARY KEY ("Id");


--
-- Name: UserAuthorisation PK_UserAuthorisation; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserAuthorisation"
    ADD CONSTRAINT "PK_UserAuthorisation" PRIMARY KEY ("Id");


--
-- Name: UsersLoginHistory PK_UsersLoginHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UsersLoginHistory"
    ADD CONSTRAINT "PK_UsersLoginHistory" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_AspNetUsers_RoleName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUsers_RoleName" ON public."AspNetUsers" USING btree ("RoleName");


--
-- Name: IX_CheckList_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CheckList_UserId" ON public."CheckList" USING btree ("UserId");


--
-- Name: IX_UserAuthorisation_UserGuid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserAuthorisation_UserGuid" ON public."UserAuthorisation" USING btree ("UserGuid");


--
-- Name: IX_UsersLoginHistory_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UsersLoginHistory_UserId" ON public."UsersLoginHistory" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUsers FK_AspNetUsers_AspNetRoles_RoleName; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "FK_AspNetUsers_AspNetRoles_RoleName" FOREIGN KEY ("RoleName") REFERENCES public."AspNetRoles"("Id") ON DELETE RESTRICT;


--
-- Name: CheckList FK_CheckList_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CheckList"
    ADD CONSTRAINT "FK_CheckList_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserAuthorisation FK_UserAuthorisation_AspNetUsers_UserGuid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserAuthorisation"
    ADD CONSTRAINT "FK_UserAuthorisation_AspNetUsers_UserGuid" FOREIGN KEY ("UserGuid") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UsersLoginHistory FK_UsersLoginHistory_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UsersLoginHistory"
    ADD CONSTRAINT "FK_UsersLoginHistory_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

